name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install -r backend/requirements.txt
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App using CLI
      run: |
        # Create a zip file of the backend
        cd backend
        zip -r ../backend-deploy.zip . -x "*.pyc" "__pycache__/*" "*.db"
        cd ..
        
        # Deploy using Azure CLI
        az webapp deployment source config-zip \
          --resource-group tejomag-rg \
          --name tejomag-backend \
          --src backend-deploy.zip
